Added a longer comment for pa11y failures.

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -40,4 +40,4 @@ jobs:
           
       - name: Check for pa11y failures.
         if: contains(steps.pa11y_output.outputs.content, 'errno 2')
-        run: exit 1
+        run: echo "Some of the URLs are failing accessibility tests. Please review the comment or the pa11y-ci step for details."; exit 1
